# This is a basic workflow to help you get started with Actions

name: Deploy to Gh-Pages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install Angular CLI globally
      - name: Install Angular CLI
        run: sudo npm i -g @angular/cli

      # Install dependencies
      - name: Run npm install
        run: npm i

      # Builds the Angular app
      - name: Build Angular
        run: |
          ng build lib
          ng build --configuration production --output-path docs --base-href /angularx-social-login/

      - uses: EndBug/add-and-commit@v7
        with:
          add: "docs"
          default_author: github_actions
          message: "Update demo application"
